name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crystal:
          - latest
          - nightly
          - 1.0.0
    runs-on: ${{ matrix.os }}
    container: crystallang/crystal:${{ matrix.crystal }}-alpine

    services:
      # Label used to access the service container
      sshdev:
        # Docker Hub image
        image: placeos/ssh-test
        options: >-
          -p 2222:22
          -e ROOT_PASS="somepassword"

    steps:
    - uses: actions/checkout@v2
    - name: Install LibSSH2
      run: apk add --no-cache libssh2 libssh2-dev libssh2-static
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Lint
      run: ./bin/ameba
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec -v --error-trace
      env:
        SPEC_SSH_HOST: sshdev
